
import requests
import json
import os
import sys
import datetime

# 配置
REPO_OWNER = "lbjlaq"
REPO_NAME = "Antigravity-Manager"
GITHUB_API_URL = f"https://api.github.com/repos/{REPO_OWNER}/{REPO_NAME}/releases"
GITHUB_TOKEN = os.environ.get("GITHUB_TOKEN") # 自动获取 Token 防止速率限制

def get_headers():
    headers = {
        "Accept": "application/vnd.github.v3+json",
        "User-Agent": "Antigravity-Release-Monitor"
    }
    if GITHUB_TOKEN:
        headers["Authorization"] = f"token {GITHUB_TOKEN}"
    return headers

def 获取所有版本():
    """获取所有 Release 信息"""
    releases = []
    page = 1
    while True:
        url = f"{GITHUB_API_URL}?per_page=100&page={page}"
        try:
            r = requests.get(url, headers=get_headers(), timeout=30)
            if r.status_code == 404:
                break
            r.raise_for_status()
            data = r.json()
            if not data:
                break
            releases.extend(data)
            page += 1
        except Exception as e:
            print(f"获取版本列表失败: {e}", file=sys.stderr)
            break
    return releases

def 获取最新版本():
    """获取最新 Release"""
    url = f"{GITHUB_API_URL}/latest"
    try:
        r = requests.get(url, headers=get_headers(), timeout=30)
        if r.status_code == 404:
            # 尝试获取列表第一个
            all_releases = 获取所有版本()
            if all_releases:
                return all_releases[0]
            return None
        r.raise_for_status()
        return r.json()
    except Exception as e:
        print(f"获取最新版本失败: {e}")
        return None

def 下载资源(assets, download_dir="."):
    """下载 Release 中的所有资源"""
    downloaded_files = []
    if not os.path.exists(download_dir):
        os.makedirs(download_dir)
        
    for asset in assets:
        name = asset["name"]
        url = asset["browser_download_url"]
        path = os.path.join(download_dir, name)
        print(f"正在下载: {name} ...")
        
        try:
            with requests.get(url, stream=True, timeout=300) as r:
                r.raise_for_status()
                with open(path, 'wb') as f:
                    for chunk in r.iter_content(chunk_size=8192):
                        f.write(chunk)
            downloaded_files.append(name)
            print(f"下载完成: {name}")
        except Exception as e:
            print(f"下载失败 {name}: {e}")
            
    return downloaded_files

def 加载历史记录():
    if os.path.exists("history.json"):
        try:
            with open("history.json", "r", encoding="utf-8") as f:
                return json.load(f)
        except:
            pass
    return []

def 保存历史记录(history):
    with open("history.json", "w", encoding="utf-8") as f:
        json.dump(history, f, indent=4, ensure_ascii=False)

def 生成README(history):
    # 按照发布时间倒序
    history.sort(key=lambda x: x.get("published_at", ""), reverse=True)
    
    current_time = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    latest = history[0] if history else {"tag_name": "Unknown", "published_at": "Unknown"}
    
    md = f"""# {REPO_NAME} 自动备份监控

> [!TIP]
> 本仓库自动监控并备份 [{REPO_OWNER}/{REPO_NAME}](https://github.com/{REPO_OWNER}/{REPO_NAME}) 的 Release 版本。
> 每小时同步一次。

## 🌟 最新版本: `{latest.get('tag_name', 'N/A')}`
**更新时间**: `{latest.get('published_at', current_time)}`

## 📜 历史版本存档
| 版本 | 发布时间 | 资源文件 | 原始链接 |
| :--- | :--- | :--- | :--- |
"""
    
    for item in history:
        tag = item.get("tag_name", "N/A")
        date = item.get("published_at", "").split("T")[0]
        url = item.get("html_url", "#")
        
        # 简单列出资产
        assets_text = ""
        if "assets" in item:
            for asset in item["assets"]:
                # 使用 release 直接下载链接（如果已在 GitHub Release 中托管）
                # 这里假设我们会上传到当前的 Release，所以链接应该指向当前 Repo 的 Release
                # 但为了简单，我们先列出文件名
                assets_text += f"`{asset['name']}`<br>"
        
        md += f"| `{tag}` | {date} | {assets_text} | [Source]({url}) |\n"

    md += "\n---\n*Auto-generated by Antigravity Monitoring System*\n"
    return md

def main():
    # 命令行模式
    if len(sys.argv) > 1:
        if sys.argv[1] == "--api-history":
            # 返回所有版本列表供 Matrix 使用
            releases = 获取所有版本()
            output = []
            for r in releases:
                # 简化数据结构以减小 JSON 大小
                output.append({
                    "version": r["tag_name"],
                    "id": r["id"],
                    "assets": r["assets"], # 包含 url 等信息
                    "body": r["body"],
                    "published_at": r["published_at"],
                    "html_url": r["html_url"]
                })
            print(json.dumps(output))
            return

        if sys.argv[1] == "--download":
            # 下载指定版本的资源
            # 用法: python check_version.py --download <json_string_of_assets>
            # 或者为了简单，重新获取指定版本
            version_tag = sys.argv[2]
            print(f"正在查找版本 {version_tag} 的资源...")
            releases = 获取所有版本()
            target_release = next((r for r in releases if r["tag_name"] == version_tag), None)
            
            if target_release:
                file_list = 下载资源(target_release["assets"])
                # 写入 step output
                if "GITHUB_OUTPUT" in os.environ:
                    with open(os.environ["GITHUB_OUTPUT"], "a") as f:
                        f.write(f"assets={' '.join(file_list)}\n")
            else:
                print(f"未找到版本 {version_tag}")
                sys.exit(1)
            return

    # 默认模式：检查更新 (Hourly Job)
    print("开始检查最新版本...")
    latest_release = 获取最新版本()
    if not latest_release:
        print("无法获取最新版本")
        sys.exit(1)

    tag_name = latest_release["tag_name"]
    published_at = latest_release["published_at"]
    
    # 读取本地版本
    local_version = ""
    if os.path.exists("VERSION"):
        with open("VERSION", "r", encoding="utf-8") as f:
            local_version = f.read().strip()
            
    print(f"本地版本: {local_version}, 远程最新: {tag_name}")
    
    # 只有当版本不同时才触发动作
    version_changed = (tag_name != local_version)
    
    # 更新历史记录 (无论是否变化，都确保历史记录是最新的)
    history = 加载历史记录()
    # 检查是否已存在
    exists = any(item["tag_name"] == tag_name for item in history)
    if not exists:
        history.insert(0, {
            "tag_name": tag_name,
            "published_at": published_at,
            "html_url": latest_release["html_url"],
            "assets": [{"name": a["name"], "browser_download_url": a["browser_download_url"]} for a in latest_release["assets"]]
        })
        保存历史记录(history)
    
    readme_content = 生成README(history)
    with open("README.md", "w", encoding="utf-8") as f:
        f.write(readme_content)
        
    # 写入 Output
    if "GITHUB_OUTPUT" in os.environ:
        with open(os.environ["GITHUB_OUTPUT"], "a") as f:
            f.write(f"version_changed={'true' if version_changed else 'false'}\n")
            f.write(f"version={tag_name}\n")
            f.write(f"body={json.dumps(latest_release['body'])}\n") # 防止多行问题，虽然json.dumps会转义
            
            if version_changed:
                print("版本更新，开始下载资源...")
                file_list = 下载资源(latest_release["assets"])
                f.write(f"assets={' '.join(file_list)}\n")
                
                # 更新本地 VERSION 文件
                with open("VERSION", "w", encoding="utf-8") as vf:
                    vf.write(tag_name)

if __name__ == "__main__":
    main()
